title: Video Recorder App
description: Application d'enregistrement vidéo
baseurl: ""
url: ""

# Build settings
markdown: kramdown
theme: jekyll-theme-primer

plugins:
  - jekyll-feed

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
